### PR TITLE
[Op] Fix dropout

### LINKED ISSUE #36: [Bug] Misuse CuDNN dropout
Based on the CuDNN manual, the `states` buffer (random number generator states) for dropout (both forward and backward) should be globally shared by all dropout calls. However, the current implementation has two issues:

1. Forward dropout makes this argument optional, and the current flow (specifically, FromRelay) doesn't specify this argument, so we never provide state buffer.
2. Backward dropout allocates state buffer for every op. This makes the state buffer meaningless.

Ideally, we have to allocate the state buffer just once and use it for ALL dropout ops in the IR. Here is one example:

```
let %state = zeros(...);
let %x1 = dropout(%data, 0.6, %state); // %state is updated inplace just like running_mean in batch_norm.
let %x2 = ...;
let %x3 = dropout(%x2, 0.6, %state);
...
let %x4 = dropout_dx(..., %state);
...
let %x5 = dropout_dx(..., %state);
```

In this way, the RNG state is maintained during an iteration. Furthermore, the RNG state should be maintained cross iterations. To do so, we have to either 1) create scratch buffers in VM context (this is how PyTorch does), or 2) make state buffer as an input parameter (this is a bit hacky because users will see this parameter and may get confused).

Reference:
[1] PyTorch CuDNN dropout: https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/caffe2/operators/dropout_op_cudnn.cc
[2] CuDNN manual: https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnSetDropoutDescriptor

cc @awslabs/raf-reviewer @yzhliu @hzfan

### PR DESCRIPTION
**Pull request by comaniac**
## Description ##

Close #36 

This PR fixes the dropout mentioned in the issue. Specifically, we use a global memory manager to maintain random state buffers. As a result, all dropout ops with the same device and ratio could share random state. Although this memory manager cannot be viewed by remat pass, it is just a few MBs so shouldn't be a big problem.

In addition, this PR also changes the `_contrib_dropout` output to be tuple-3 by removing the `out_state`. This has no effect because 1) we don't use this output at all, and 2) the CuDNN dropout OpEnv updates the state inplace, and it doesn't actually copy the state to this output buffer, so it's meaningless.

Finally, this PR removes the trick in AssignDevice pass that adds the optional argument (i.e., `in_states`). Instead, we just don't specify this argument in VM and always use the memory manager one. Meanwhile, this argument is still kept so that we could use interpreter to reproduce dropout results.

## Checklist ##

- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

cc @awslabs/raf-reviewer @yzhliu @hzfan @hgt312

### CODE REVIEW

File: src/op/dialect/cudnn/dropout.cc [hunk 1]
```diff
@@ -73,24 +115,46 @@ class DropoutImplementedByCUDNNDropoutForward : public raf::op::OpEnv {
...
-        cudnnDropoutGetStatesSize(CUDNNThreadEntry::ThreadLocal()->handle, &stateSizeInBytes));
+    stateSizeInBytes = GetDropoutStateSizeInBytes();
     CUDNN_CALL(cudnnDropoutGetReserveSpaceSize(xdesc, &reserveSpaceSizeInBytes));
-    CUDNN_CALL(cudnnRestoreDropoutDescriptor(dropoutDesc, CUDNNThreadEntry::ThreadLocal()->handle,
-                                             dropout, state->data, stateSizeInBytes, 0));
+
+    if (is_first_dropout) {
+      // Initial dropout desc with a certain ratio. This desc will be shared by all dropout ops
+      // with the same ratio.
+      auto seed = tvm::support::LinearCongruentialEngine::DeviceRandom();
```
Comment (yzhliu) [inline src/op/dialect/cudnn/dropout.cc:149]: this is cool.

File: tests/python/op/cudnn/test_cudnn_nn.py [hunk 2]
```diff
@@ -267,7 +266,7 @@ def forward(self, m_x, m_m, m_v, m_w, m_b):
     check(m_b.grad, t_b.grad, rtol=rtol, atol=atol)
 
 
-@with_dialect(["cudnn", "tvm"])
+@with_dialect(["cudnn"])
```
Comment (yzhliu) [inline tests/python/op/cudnn/test_cudnn_nn.py:269]: does it still work with tvm?

Comment (comaniac) [reply tests/python/op/cudnn/test_cudnn_nn.py:269]: I think so although I didn't verify. On the other hand, TVM dialect won't be tested in this case anyways.

**Review by hgt312 — APPROVED** [review]
Otherwise LGTM

File: src/op/declare/nn.cc [hunk 3]
```diff
@@ -425,14 +425,10 @@ void ContribDropout(const CallValues& call) {
                                            /*dtype=*/DType(DTypeCode::kFloat(), 32),
                                            /*shape=*/mask_shape);
   // valid for cudnn only
-  TensorValue out_states = TensorValue::Assemble(/*dev=*/x->device,
-                                                 /*dtype=*/DType(DTypeCode::kUInt(), 8),
-                                                 /*shape=*/states_shape);
```
[the remark this answers is not in the document]
Comment (comaniac) [reply src/op/declare/nn.cc:430]: Good catch. Removed.

File: src/op/dialect/cudnn/dropout.cc [hunk 4]
```diff
@@ -73,24 +115,46 @@ class DropoutImplementedByCUDNNDropoutForward : public raf::op::OpEnv {
...
+
+    bool is_first_dropout = false;
+    if (args->in_states.get() == nullptr) {
+      // If no state is provided, use the internal one.
+      auto state_n_init = DropoutStatePool::Get(cv->device)->GetState(dropout);
+      auto buf = state_n_init.first;
+      is_first_dropout = state_n_init.second;
+      state_data = buf->data;
+    } else {
+      DLTensor* state_tensor = args->in_states.value();
```
[the remark this answers is not in the document]
Comment (comaniac) [reply src/op/dialect/cudnn/dropout.cc:137]: This is supposed to be used for debugging/reproducing only. As the unit test shows, we expect this state to come from `raf.backend.cudnn.GetDropoutState` and is already initialized. Thus, we assume the user-given state is already initialized and use "restore" here.

**Review by yzhliu — APPROVED** [review]
Thanks @comaniac @hgt312
